#git_repository(
#    name = "org_pubref_rules_protobuf",
#    commit = "d9523f3d443b6a4f3fabc72051d84eb5474d7745",
#    remote = "https://github.com/pubref/rules_protobuf.git",
#)

# use a local repository instead
# https://github.com/llatseattle/rules_protobuf.git
git_repository(
    name = "org_pubref_rules_protobuf",
    remote = "https://github.com/llatseattle/rules_protobuf.git",
    commit = "794e303a631a12d8872358057e845bff0f9d34e8",
)

load("@org_pubref_rules_protobuf//protobuf:rules.bzl", "proto_repositories")
proto_repositories()

load("@org_pubref_rules_protobuf//cpp:rules.bzl", "cpp_proto_repositories")
cpp_proto_repositories()

load("@org_pubref_rules_protobuf//python:rules.bzl", "py_proto_repositories")
py_proto_repositories()

new_http_archive(
    name = "gtest",
    url = "https://github.com/google/googletest/archive/release-1.8.0.zip",
    build_file = "third_party/gtest/BUILD",
    strip_prefix = "googletest-release-1.8.0",
)

# for python runtime support
# 1-A. Pull down rules_python
#http_archive(
#    name = "io_bazel_rules_python",
#    url = "https://github.com/bazelbuild/rules_python/archive/07fba0f91bb5898d19daeaabf635d08059f7eacd.zip",
#    sha256 = "53fecb9ddc5d3780006511c9904ed09c15a8aed0644914960db89f56b1e875bd",
#    strip_prefix = "rules_python-07fba0f91bb5898d19daeaabf635d08059f7eacd",
#)

# use my own fork
git_repository(
    name = "io_bazel_rules_python",
    remote = "https://github.com/llatseattle/rules_python.git",
    commit = "4dd4b2eaf7a0896282760b659342eb35683982c8",
)

# 1-B. Load the skylark file containing the needed functions
load("@io_bazel_rules_python//python:pip.bzl", "pip_repositories", "pip_import")

# 1-C. Invoke pip_repositories to load rules_python internal dependencies
pip_repositories()

# 1-D. Invoke pip_import with the necessary python requirements.  You can refer to the
# one in rules_protobuf, or roll your own (make sure it includes 'grpcio==1.6.0' (or later)).
pip_import(
   name = "pip_grpcio",
   requirements = "@org_pubref_rules_protobuf//python:requirements.txt",
)

# 1-E. Load the requirements.bzl file that will be written in this new workspace
# defined in 1-D.
load("@pip_grpcio//:requirements.bzl", pip_grpcio_install = "pip_install")

# 1-F. Invoke this new function to trigger pypi install of 'grpcio' when needed.
pip_grpcio_install()